apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cluster-scheduler
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cluster-scheduler
    spec:
      containers:
      - name: cluster-scheduler
        image: registry.dev.rafay-edge.net:5000/azhou/cluster-scheduler:master-20190905-2145
        imagePullPolicy: "Always"
      imagePullSecrets:
        - name: dev-registry-creds
