apiVersion: v1
kind: Service
metadata:
  name: cluster-scheduler-api
  labels:
    app: cluster-scheduler
spec:
  ports:
   - port: 8000
     targetPort: : 8000
  selector:
   app: cluster-scheduler

---

apiVersion: v1
kind: Service
metadata:
  name: cluster-scheduler-grpc
  labels:
    app: cluster-scheduler
spec:
  ports:
   - port: 5000
     targetPort: : 5000
  selector:
   app: cluster-scheduler

---

apiVersion: v1
kind: Service
metadata:
  name: cluster-scheduler-connector
  labels:
    app: cluster-scheduler
spec:
  ports:
   - port: 5002
     targetPort: : 5002
  selector:
   app: cluster-scheduler

