apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cluster-scheduler
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cluster-scheduler
    spec:
      containers:
        - name: cluster-scheduler
          image: registry.dev.refay.cloud/rafay/cluster-scheduler:azhou-master-latest
          imagePullPolicy: "always"
        imagePullSecrets:
        - name: dev-registry-creds
